import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e4e2e1',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#54433c',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#87736a',
        'outline-variant': '#dac1b7',
        'surface-tint': '#944a23',
        primary: '#78350f', // deep espresso
        'on-primary': '#ffffff',
        'primary-container': '#78350f',
        'on-primary-container': '#ffa072',
        'inverse-primary': '#ffb693',
        secondary: '#d97706', // warm amber
        'on-secondary': '#ffffff',
        'secondary-container': '#fe932c',
        'on-secondary-container': '#663500',
        tertiary: '#0d9488', // high-bandwidth teal
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00524b',
        'on-tertiary-container': '#5bc9bc',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdbcc',
        'primary-fixed-dim': '#ffb693',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#76330d',
        'secondary-fixed': '#ffdcc3',
        'secondary-fixed-dim': '#ffb77d',
        'on-secondary-fixed': '#2f1500',
        'on-secondary-fixed-variant': '#6e3900',
        'tertiary-fixed': '#89f5e7',
        'tertiary-fixed-dim': '#6bd8cb',
        'on-tertiary-fixed': '#00201d',
        'on-tertiary-fixed-variant': '#005049',
        background: '#fcf9f8',
        'on-background': '#1b1c1c',
        'surface-variant': '#e4e2e1',
        neutral: '#262626',
        'canvas-gray': '#f7f7f7',
        'canvas-surface': '#f1f3f5',
        'wifi-bg': '#f0fdfa',
        'wifi-text': '#0d9488',
        'power-bg': '#ecfdf5',
        'power-text': '#059669',
        'noise-bg': '#eef2ff',
        'noise-text': '#4f46e5',
        mapWater: "#d6e5f3", // kept for map
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        bungee: ["var(--font-bungee)", "cursive"],
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        '3xl': '1.5rem', // Used in shapes description
        full: '9999px',
      },
      spacing: {
        gutter: '1rem',
        'gutter-lg': '1.5rem',
        margin: '1rem',
        'margin-md': '1.5rem',
        'margin-lg': '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      boxShadow: {
        'level-1': '0 4px 20px -2px rgba(38, 38, 38, 0.05)',
        'level-2': '0 12px 32px -4px rgba(120, 53, 15, 0.08)',
        'level-3': '0 16px 40px -6px rgba(0, 0, 0, 0.1)',
      },
      letterSpacing: {
        'tighter': '-0.03em',
        'tight': '-0.02em',
        'normal': '-0.005em',
        'wide': '0.01em',
        'wider': '0.03em',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      }
    },
  },
  plugins: [],
};
export default config;
